# Generated by Django 5.1.5 on 2025-01-22 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="course_categories/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Category",
                "verbose_name_plural": "Course Categories",
                "db_table": "course_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="QuestionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Question Category",
                "verbose_name_plural": "Question Categories",
                "db_table": "question_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sort_number", models.PositiveIntegerField(db_index=True, default=0)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(db_index=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, db_index=True, null=True, upload_to="courses/"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("lesson_count", models.PositiveIntegerField(db_index=True)),
                ("students_count", models.PositiveIntegerField(db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_paid", models.BooleanField(db_index=True, default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="mobile.coursecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "db_table": "courses",
                "ordering": ["sort_number"],
            },
        ),
        migrations.CreateModel(
            name="CourseLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sort_number", models.PositiveIntegerField(db_index=True, default=0)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(db_index=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="mobile.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Lesson",
                "verbose_name_plural": "Course Lessons",
                "db_table": "course_lessons",
                "ordering": ["sort_number"],
            },
        ),
        migrations.CreateModel(
            name="CourseLessonResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("file", models.FileField(db_index=True, upload_to="course_lessons/")),
                ("size", models.PositiveIntegerField(db_index=True, default=0)),
                ("type", models.CharField(db_index=True, max_length=255)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="mobile.courselesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Lesson Resource",
                "verbose_name_plural": "Course Lesson Resources",
                "db_table": "course_lesson_resources",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_number",
                    models.PositiveIntegerField(
                        auto_created=True, db_index=True, default=0
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(db_index=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="mobile.questioncategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "db_table": "questions",
                "ordering": ["sort_number"],
            },
        ),
    ]
