# Generated by Django 5.1.5 on 2025-03-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0003_questionnaire_questionnairecategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaireanswer",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Is active"
            ),
        ),
    ]
