# Generated by Django 5.1.5 on 2025-01-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0003_coursecategory_is_active_courselesson_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="sort_number",
            field=models.PositiveIntegerField(auto_created=True, db_index=True),
        ),
    ]
