# Generated by Django 5.1.5 on 2025-03-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0004_questionnaireanswer_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="question_en",
            field=models.TextField(db_index=True, null=True, verbose_name="Question"),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="question_ru",
            field=models.TextField(db_index=True, null=True, verbose_name="Question"),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="question_uz",
            field=models.TextField(db_index=True, null=True, verbose_name="Question"),
        ),
        migrations.AddField(
            model_name="questionnaireanswer",
            name="answer_en",
            field=models.TextField(db_index=True, null=True, verbose_name="Answer"),
        ),
        migrations.AddField(
            model_name="questionnaireanswer",
            name="answer_ru",
            field=models.TextField(db_index=True, null=True, verbose_name="Answer"),
        ),
        migrations.AddField(
            model_name="questionnaireanswer",
            name="answer_uz",
            field=models.TextField(db_index=True, null=True, verbose_name="Answer"),
        ),
        migrations.AddField(
            model_name="questionnairecategory",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="questionnairecategory",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="questionnairecategory",
            name="description_uz",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="questionnairecategory",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="questionnairecategory",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="questionnairecategory",
            name="title_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
    ]
