# Generated by Django 5.1.5 on 2025-01-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0004_alter_question_sort_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="sort_number",
            field=models.PositiveIntegerField(
                db_index=True, verbose_name="Sort number"
            ),
        ),
    ]
