# Generated by Django 5.1.5 on 2025-03-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0005_questionnaire_question_en_questionnaire_question_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="is_text_answer",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Is text answer"
            ),
        ),
        migrations.AlterField(
            model_name="questionnaireuseranswer",
            name="answer_text",
            field=models.TextField(
                blank=True, db_index=True, null=True, verbose_name="Answer text"
            ),
        ),
    ]
