# Generated by Django 5.1.5 on 2025-01-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0006_alter_course_lesson_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courselessonresource",
            name="name",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="courselessonresource",
            name="type",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
