# Generated by Django 5.1.5 on 2025-03-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0006_questionnaire_is_text_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionnairecategory",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="questionnairecategory",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="questionnairecategory",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="questionnairecategory",
            name="description_uz",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
    ]
