# Generated by Django 5.1.5 on 2025-01-25 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0007_alter_courselessonresource_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saved",
            name="course",
        ),
        migrations.RemoveField(
            model_name="courselesson",
            name="course",
        ),
        migrations.AlterModelOptions(
            name="courselesson",
            options={
                "ordering": ["sort_number"],
                "verbose_name": "Course Lesson",
                "verbose_name_plural": "Courses Lessons",
            },
        ),
        migrations.AddField(
            model_name="courselesson",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="mobile.coursecategory",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="courselesson",
            name="image",
            field=models.ImageField(
                blank=True, db_index=True, null=True, upload_to="courses/"
            ),
        ),
        migrations.AddField(
            model_name="courselesson",
            name="is_paid",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="courselesson",
            name="lesson_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="courselesson",
            name="saved_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="courselesson",
            name="students_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="saved",
            name="lesson",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved",
                to="mobile.courselesson",
            ),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="courselesson",
            table="courses_lessons",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
    ]
