# Generated by Django 5.1.5 on 2025-03-19 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0007_alter_questionnairecategory_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionnaireuseranswer",
            name="answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_answers",
                to="mobile.questionnaireanswer",
            ),
        ),
    ]
