# Generated by Django 5.0.8 on 2025-01-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0008_remove_saved_course_remove_courselesson_course_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursecategory",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Course Category",
                "verbose_name_plural": "Course Categories",
            },
        ),
        migrations.RenameField(
            model_name="coursecategory",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="courselesson",
            name="is_paid",
        ),
        migrations.RemoveField(
            model_name="courselesson",
            name="lesson_count",
        ),
        migrations.RemoveField(
            model_name="courselesson",
            name="saved_count",
        ),
        migrations.RemoveField(
            model_name="courselesson",
            name="students_count",
        ),
        migrations.AddField(
            model_name="coursecategory",
            name="description",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="coursecategory",
            name="lesson_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="coursecategory",
            name="saved_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="coursecategory",
            name="students_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="coursecategory",
            name="sub_title",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
