# Generated by Django 5.1.5 on 2025-03-19 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0008_alter_questionnaireuseranswer_answer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionnaireuseranswer",
            name="answer",
        ),
        migrations.RemoveField(
            model_name="questionnaireuseranswer",
            name="answer_text",
        ),
        migrations.RemoveField(
            model_name="questionnaireuseranswer",
            name="questionnaire",
        ),
        migrations.CreateModel(
            name="QuestionnaireUserAnswerDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "answer_text",
                    models.TextField(
                        blank=True, db_index=True, null=True, verbose_name="Answer text"
                    ),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answers",
                        to="mobile.questionnaireanswer",
                    ),
                ),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answers",
                        to="mobile.questionnaire",
                    ),
                ),
                (
                    "user_answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answer_details",
                        to="mobile.questionnaireuseranswer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Questionnaire User Answer Detail",
                "verbose_name_plural": "Questionnaire User Answer Details",
                "db_table": "questionnaire_user_answer_detail",
                "ordering": ("-created_at",),
            },
        ),
    ]
