# Generated by Django 5.1.5 on 2025-03-19 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0009_remove_questionnaireuseranswer_answer_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questionnaireuseranswer",
            options={
                "ordering": ("-updated_at",),
                "verbose_name": "Questionnaire User Answer",
                "verbose_name_plural": "Questionnaire User Answers",
            },
        ),
        migrations.AlterModelOptions(
            name="questionnaireuseranswerdetail",
            options={
                "ordering": ("-updated_at",),
                "verbose_name": "Questionnaire User Answer Detail",
                "verbose_name_plural": "Questionnaire User Answer Details",
            },
        ),
        migrations.AddField(
            model_name="questionnaireuseranswer",
            name="category",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_answers",
                to="mobile.questionnairecategory",
            ),
            preserve_default=False,
        ),
    ]
