# Generated by Django 5.1.5 on 2025-01-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0009_alter_coursecategory_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursecategory",
            name="saved_count",
        ),
        migrations.RemoveField(
            model_name="coursecategory",
            name="students_count",
        ),
        migrations.AddField(
            model_name="courselesson",
            name="likes_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="courselesson",
            name="students_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="courselesson",
            name="image",
            field=models.ImageField(
                blank=True, db_index=True, null=True, upload_to="lessons/"
            ),
        ),
        migrations.AlterField(
            model_name="courselessonresource",
            name="file",
            field=models.FileField(db_index=True, upload_to="lesson_resource/"),
        ),
        migrations.AlterField(
            model_name="courselessonresource",
            name="size",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
