# Generated by Django 5.1.5 on 2025-01-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0010_remove_coursecategory_saved_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courselesson",
            name="audio_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="courselesson",
            name="document_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="courselesson",
            name="test_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="courselesson",
            name="text",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="courselesson",
            name="video_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="courselessonresource",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("document", "Document"),
                ],
                db_index=True,
                max_length=255,
                null=True,
            ),
        ),
    ]
