# Generated by Django 5.1.5 on 2025-03-19 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0010_alter_questionnaireuseranswer_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questionnaire",
            options={
                "ordering": ("created_at",),
                "verbose_name": "Questionnaire",
                "verbose_name_plural": "Questionnaires",
            },
        ),
    ]
