# Generated by Django 5.1.5 on 2025-03-24 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0011_alter_questionnaire_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questionnairecategory",
            options={
                "ordering": ("created_at",),
                "verbose_name": "Questionnaire Category",
                "verbose_name_plural": "Questionnaires Category",
            },
        ),
        migrations.AlterModelTable(
            name="questionnairecategory",
            table="questionnaire_category",
        ),
    ]
