# Generated by Django 5.1.5 on 2025-01-25 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0013_alter_courselessonresource_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="mobile.courselesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test",
                "verbose_name_plural": "Tests",
                "db_table": "test",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TestQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.TextField(verbose_name="Question")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="mobile.test",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "db_table": "question",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("answer", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[("RADIO", "Radio"), ("CHECKBOX", "Checkbox")],
                        default="RADIO",
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                ("ball", models.IntegerField(default=0, verbose_name="Ball")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Is correct"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="mobile.testquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer",
                "verbose_name_plural": "Answers",
                "db_table": "answer",
                "ordering": ("-created_at",),
            },
        ),
    ]
