# Generated by Django 5.1.5 on 2025-01-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0014_test_testquestion_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="questioncategory",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="question_categories/"
            ),
        ),
    ]
