# Generated by Django 5.1.5 on 2025-01-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0015_questioncategory_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecategory",
            name="first_color",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="coursecategory",
            name="second_color",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
