# Generated by Django 5.1.5 on 2025-01-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0016_coursecategory_first_color_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="banners/"),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Banner",
                "verbose_name_plural": "Banners",
                "db_table": "banners",
                "ordering": ["-created_at"],
            },
        ),
    ]
