# Generated by Django 5.1.5 on 2025-01-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0018_help"),
    ]

    operations = [
        migrations.AddField(
            model_name="help",
            name="status",
            field=models.CharField(
                choices=[("SAFE", "Safe"), ("DANGER", "Danger")],
                default="SAFE",
                max_length=6,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="link",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="link"
            ),
        ),
    ]
