# Generated by Django 5.1.5 on 2025-01-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0019_help_status_alter_banner_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="help",
            name="message",
        ),
    ]
