# Generated by Django 5.1.5 on 2025-01-29 11:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0020_remove_help_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="saved",
            unique_together={("user", "lesson")},
        ),
    ]
