# Generated by Django 5.1.5 on 2025-01-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0021_alter_saved_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="courselessonresource",
            name="banner",
            field=models.ImageField(
                blank=True,
                db_index=True,
                null=True,
                upload_to="lesson_resource/banner/",
            ),
        ),
        migrations.AddField(
            model_name="courselessonresource",
            name="description",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
