# Generated by Django 5.1.5 on 2025-01-31 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0022_courselessonresource_banner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="test"),
        ),
        migrations.AddField(
            model_name="test",
            name="question_count",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
