# Generated by Django 5.1.5 on 2025-01-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0023_test_banner_test_question_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="answer",
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name="answer",
            name="ball",
            field=models.IntegerField(db_index=True, default=0, verbose_name="Ball"),
        ),
        migrations.AlterField(
            model_name="answer",
            name="is_correct",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Is correct"
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="type",
            field=models.CharField(
                choices=[("RADIO", "Radio"), ("CHECKBOX", "Checkbox")],
                db_index=True,
                default="RADIO",
                max_length=10,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="banner",
            field=models.ImageField(
                blank=True, db_index=True, null=True, upload_to="test"
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="question_count",
            field=models.PositiveBigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="testquestion",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Is active"
            ),
        ),
        migrations.AlterField(
            model_name="testquestion",
            name="question",
            field=models.TextField(db_index=True, verbose_name="Question"),
        ),
    ]
