# Generated by Django 5.1.5 on 2025-02-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0030_help_is_send"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="help",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "help",
                "verbose_name_plural": "helps",
            },
        ),
        migrations.AddField(
            model_name="news",
            name="view_count",
            field=models.PositiveBigIntegerField(default=0, verbose_name="view count"),
        ),
        migrations.AlterModelTable(
            name="help",
            table="helps",
        ),
    ]
