# Generated by Django 5.1.5 on 2025-02-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0031_alter_help_options_news_view_count_alter_help_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="help",
            options={"verbose_name": "help", "verbose_name_plural": "helps"},
        ),
        migrations.AlterField(
            model_name="news",
            name="view_count",
            field=models.PositiveBigIntegerField(
                blank=True,
                db_index=True,
                default=0,
                null=True,
                verbose_name="view count",
            ),
        ),
    ]
