# Generated by Django 5.1.5 on 2025-02-08 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0032_alter_help_options_alter_news_view_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="VictimStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="name"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="is active"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="victim",
            name="answer",
            field=models.TextField(
                blank=True, db_index=True, null=True, verbose_name="answer"
            ),
        ),
        migrations.AddField(
            model_name="victim",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="victims",
                to="mobile.victimstatus",
                verbose_name="status",
            ),
        ),
    ]
