# Generated by Django 5.1.5 on 2025-02-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0033_victimstatus_victim_answer_victim_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="victim",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "victim",
                "verbose_name_plural": "victims",
            },
        ),
        migrations.AlterModelOptions(
            name="victimstatus",
            options={
                "ordering": ["name"],
                "verbose_name": "victim status",
                "verbose_name_plural": "victim statuses",
            },
        ),
        migrations.AddField(
            model_name="victimstatus",
            name="name_en",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="victimstatus",
            name="name_ru",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="victimstatus",
            name="name_uz",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="name"
            ),
        ),
        migrations.AlterModelTable(
            name="victim",
            table="victims",
        ),
        migrations.AlterModelTable(
            name="victimstatus",
            table="victim_statuses",
        ),
    ]
