# Generated by Django 5.1.5 on 2025-02-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0035_remove_victimstatus_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="victimstatus",
            name="is_pending",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="is pending"
            ),
        ),
    ]
