# Generated by Django 5.1.5 on 2025-02-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0037_about_aboutproject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecategory",
            name="sub_title",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="coursecategory",
            name="sub_title_en",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="coursecategory",
            name="sub_title_ru",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="coursecategory",
            name="sub_title_uz",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="coursecategory",
            name="title",
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name="coursecategory",
            name="title_en",
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="coursecategory",
            name="title_ru",
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="coursecategory",
            name="title_uz",
            field=models.TextField(db_index=True, null=True),
        ),
    ]
