# Generated by Django 5.1.5 on 2025-01-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_premium",
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[("SINGLE", "Single"), ("ALL", "All"), ("NONE", "None")],
                default="SINGLE",
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
