# Generated by Django 5.1.5 on 2025-01-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_is_premium_alter_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="message_en",
            field=models.TextField(db_index=True, null=True, verbose_name="Message"),
        ),
        migrations.AddField(
            model_name="notification",
            name="title_en",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
    ]
