# Generated by Django 5.1.5 on 2025-01-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_notification_message_en_notification_title_en"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="register_type",
            field=models.CharField(
                choices=[
                    ("PHONE", "Telefon"),
                    ("GOOGLE", "Google"),
                    ("APPLE", "Apple"),
                ],
                db_index=True,
                default="PHONE",
                max_length=20,
                verbose_name="Ro'yxatdan o'tish turi",
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="provider",
            field=models.CharField(
                choices=[
                    ("PHONE", "Telefon"),
                    ("GOOGLE", "Google"),
                    ("APPLE", "Apple"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Provider",
            ),
        ),
    ]
