# Generated by Django 5.1.5 on 2025-01-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_register_type_alter_userdata_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("USER", "Foydalanuvchi")],
                default="USER",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
