# Generated by Django 5.1.5 on 2025-02-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("USER", "Foydalanuvchi"),
                    ("SUPER_ADMIN", "Super admin"),
                ],
                default="USER",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
