# Generated by Django 5.1.5 on 2025-02-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sos_count",
            field=models.PositiveBigIntegerField(
                blank=True,
                db_index=True,
                default=0,
                null=True,
                verbose_name="SOS count",
            ),
        ),
    ]
