# Generated by Django 5.1.5 on 2025-02-13 05:59

import apps.shared.encoders.encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_sos_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="extra_data",
            field=models.JSONField(
                blank=True,
                db_index=True,
                encoder=apps.shared.encoders.encoder.PrettyJSONEncoder,
                null=True,
                verbose_name="Extra data",
            ),
        ),
    ]
