# Generated by Django 5.1.5 on 2025-02-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Fayl nomi.", max_length=255)),
                (
                    "file",
                    models.FileField(
                        help_text="Foydalanuvchi yuborgan fayl.",
                        upload_to="chat_resources/",
                    ),
                ),
                (
                    "size",
                    models.PositiveBigIntegerField(
                        blank=True, help_text="Fayl hajmi (byte).", null=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, help_text="Fayl turi.", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Chat nomi.", max_length=255, null=True
                    ),
                ),
                (
                    "message_count",
                    models.PositiveBigIntegerField(
                        default=0, help_text="O'qilmagan xabarlar soni."
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Room",
                "verbose_name_plural": "Chat Rooms",
                "db_table": "chat_rooms",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message",
                    models.TextField(blank=True, help_text="Xabar matni.", null=True),
                ),
                (
                    "is_admin",
                    models.BooleanField(
                        default=False,
                        help_text="Xabar admin tomonidan yuborilganligini bildiradi.",
                    ),
                ),
                (
                    "is_sent",
                    models.BooleanField(
                        default=False, help_text="Xabar yuborilganligini bildiradi."
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False, help_text="Xabar o'qilganligini bildiradi."
                    ),
                ),
                (
                    "is_received",
                    models.BooleanField(
                        default=False,
                        help_text="Xabar qabul qilinayotganligini bildiradi.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "db_table": "messages",
                "ordering": ["created_at"],
            },
        ),
    ]
