# Generated by Django 5.1.5 on 2025-01-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatroom",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Chat Room",
                "verbose_name_plural": "Chat Rooms",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
        migrations.AlterModelTable(
            name="chatroom",
            table="chat_rooms",
        ),
        migrations.AlterModelTable(
            name="message",
            table="messages",
        ),
    ]
