# Generated by Django 5.1.5 on 2025-01-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_rename_chat_room_message_chat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_sent",
            field=models.BooleanField(
                default=False, help_text="Xabar yuborilganligini bildiradi."
            ),
        ),
    ]
