# Generated by Django 5.1.5 on 2025-01-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_chatresource_alter_message_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatresource",
            name="size",
            field=models.PositiveBigIntegerField(
                blank=True, help_text="Fayl hajmi (byte).", null=True
            ),
        ),
    ]
