# Generated by Django 5.1.5 on 2025-01-25 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_alter_chatresource_size"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
    ]
