# Generated by Django 5.1.5 on 2025-02-07 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_alter_message_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="last_message",
            field=models.ForeignKey(
                blank=True,
                help_text="Chatdagi oxirgi xabar.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_message",
                to="chat.message",
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="message_count",
            field=models.PositiveBigIntegerField(
                default=0, help_text="O'qilmagan xabarlar soni."
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(
                default=False, help_text="Xabar o'qilganligini bildiradi."
            ),
        ),
    ]
