# Generated by Django 5.1.5 on 2025-02-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_chatroom_last_message_chatroom_message_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_received",
            field=models.BooleanField(
                default=False, help_text="Xabar qabul qilinayotganligini bildiradi."
            ),
        ),
    ]
